SELECT 
    FDOC.DNUM AS NumeroTicket,
    FDOC.DFECHA AS Fecha,
    FDOC.DCANT AS MontoSinIVA,
    (FDOC.DCANT + FDOC.DIVA) AS MontoConIVA,
    FDOC.DPAR1 AS Vendedor,
    FCLI.CLINOM AS Cliente,
    FINV.ICOD AS SKU,
    FINV.IDESCR AS Descripcion,
    FAXINV.AICANTF AS Cantidad,
    FAXINV.AIALMACEN AS Almacen,
    FINV.ILISTA3 AS PrecioLista,
    FINV.IFAM3 AS Talla,
    FINV.IFAM4 AS Color,
    FINV.IFAM5 AS Temporada
FROM 
    DOCUMENTOS AS FDOC
INNER JOIN 
    CLIENTES AS FCLI ON FDOC.CLICOD = FCLI.CLICOD
INNER JOIN
    AUXILIAR_DE_INVENTARIOS AS FAXINV ON FDOC.DNUM = FAXINV.FMOV
INNER JOIN
    INVENTARIOS AS FINV ON FAXINV.ICOD = FINV.ICOD
