SELECT 
    FDOC.DNUM AS Numero_Ticket,
    FDOC.DFECHA AS Fecha,
    FDOC.DCANT AS Monto_Sin_IVA,
    (FDOC.DCANT + FDOC.DIVA) AS Monto_Con_IVA,
    FDOC.DPAR1 AS Vendedor,
    FCLI.CLINOM AS Cliente,
    FINV.ICOD AS SKU,
    FINV.IDESCR AS Descripcion,
    FAXINV.AICANTF AS Cantidad,
    FAXINV.AIALMACEN AS Almacen,
    FINV.ILISTA3 AS Precio_Lista,
    FINV.IFAM3 AS Talla,
    FINV.IFAM4 AS Color,
    FINV.IFAM5 AS Temporada
FROM 
    DOCUMENTOS FDOC
JOIN 
    CLIENTES FCLI ON FDOC.CLICOD = FCLI.CLICOD
JOIN 
    AUXILIAR DE INVENTARIOS FAXINV ON FDOC.DNUM = FAXINV.FMOV
JOIN 
    INVENTARIOS FINV ON FAXINV.ICOD = FINV.ICOD
